"""lead coordinates

Revision ID: 30486590b034
Revises: 7d2caa8f22a2
Create Date: 2026-10-03 15:23:46.848429
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '30486590b034'
down_revision: str | None = '7d2caa8f22a2'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('leads', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('leads', sa.Column('geo_status', sa.String(length=12), nullable=True))
    op.create_index(op.f('ix_leads_geo_status'), 'leads', ['geo_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leads_geo_status'), table_name='leads')
    op.drop_column('leads', 'geo_status')
    op.drop_column('leads', 'lng')
    op.drop_column('leads', 'lat')
    # ### end Alembic commands ###
