"""lead event fields

Revision ID: 7d2caa8f22a2
Revises: 4aa15356bfeb
Create Date: 2026-10-03 14:14:47.890565
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '7d2caa8f22a2'
down_revision: str | None = '4aa15356bfeb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_events', sa.Column('fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_events', 'fields')
    # ### end Alembic commands ###
